// import axios from "axios";

// export const getProducts = async () => {
//   const res = await axios.get("https://fakestoreapi.com/products");
//   return res.data;
// };
export const items = [
  {
    id: 1,
    title: "Black Slim Fit T-Shirt",
    price: 699,
    type: "tops",
    src: "/products/tops/top1.webp",
  },
  {
    id: 2,
    title: "White Crew Neck T-Shirt",
    price: 749,
    type: "tops",
    src: "/products/tops/top2.jpg",
  },
  {
    id: 3,
    title: "Grey Cotton T-Shirt",
    price: 599,
    type: "tops",
    src: "/products/tops/top3.jpg",
  },
  {
    id: 4,
    title: "Navy Blue V-Neck Tee",
    price: 799,
    type: "tops",
    src: "/products/tops/top4.png",
  },
  {
    id: 5,
    title: "Striped Slim Fit Tee",
    price: 899,
    type: "tops",
    src: "/products/tops/top5.png",
  },
  {
    id: 6,
    title: "Denim Blue Jeans",
    price: 1499,
    type: "bottoms",
    src: "/products/bottoms/bottom1.webp",
  },
  {
    id: 7,
    title: "Black Slim Fit Trousers",
    price: 1599,
    type: "bottoms",
    src: "/products/bottoms/bottom2.webp",
  },
  {
    id: 8,
    title: "Beige Chino Pants",
    price: 1399,
    type: "bottoms",
    src: "/products/bottoms/bottom3.jpg",
  },
  {
    id: 9,
    title: "Grey Joggers",
    price: 1199,
    type: "bottoms",
    src: "/products/bottoms/bottom4.png",
  },
  {
    id: 10,
    title: "Dark Wash Jeans",
    price: 1699,
    type: "bottoms",
    src: "/products/bottoms/bottom5.png",
  },
  {
    id: 11,
    title: "Classic Black Belt",
    price: 499,
    type: "accessories",
    src: "/products/accessories/belt.jpg",
  },
  {
    id: 12,
    title: "Brown Leather Belt",
    price: 549,
    type: "accessories",
    src: "/products/accessories/belt2.webp",
  },
  {
    id: 13,
    title: "Navy Blue Cap",
    price: 399,
    type: "accessories",
    src: "/products/accessories/cap.png",
  },
  {
    id: 14,
    title: "Stylish Summer Hat",
    price: 449,
    type: "accessories",
    src: "/products/accessories/hat.png",
  },
  {
    id: 15,
    title: "Retro Sunglasses",
    price: 999,
    type: "accessories",
    src: "/products/accessories/sunglasses.jpg",
  },
  {
    id: 16,
    title: "Classic Wayfarers",
    price: 899,
    type: "accessories",
    src: "/products/accessories/sunglasses.jpg",
  },
  {
    id: 17,
    title: "White Running Shoes",
    price: 2199,
    type: "shoes",
    src: "/products/shoes/shoes1.webp",
  },
  {
    id: 18,
    title: "Black Sports Sneakers",
    price: 2499,
    type: "shoes",
    src: "/products/shoes/shoes2.webp",
  },
  {
    id: 19,
    title: "Casual Canvas Shoes",
    price: 1799,
    type: "shoes",
    src: "/products/shoes/shoes3.jpg",
  },
  {
    id: 20,
    title: "Brown Leather Boots",
    price: 2999,
    type: "shoes",
    src: "/products/shoes/shoes4.jpg",
  },
  {
    id: 21,
    title: "Slip-On Sneakers",
    price: 1999,
    type: "shoes",
    src: "/products/shoes/shoes5.png",
  },
];
